// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
)

type User struct {
	ID      int64          `json:"id"`
	Name    string         `json:"name"`
	Age     int32          `json:"age"`
	Email   string         `json:"email"`
	Phone   string         `json:"phone"`
	Address string         `json:"address"`
	City    string         `json:"city"`
	Work    sql.NullString `json:"work"`
}
